# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment1',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment1',
        ),
    ]
