# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170415_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name': '评论列表'},
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=0, verbose_name='评论层级'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.BigIntegerField(default=0, verbose_name='父级评论id'),
        ),
    ]
