# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170421_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(auto_created=True, default=0),
        ),
    ]
