# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='1', upload_to='media_pic'),
            preserve_default=False,
        ),
    ]
