# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_headimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headimage',
            field=models.ImageField(default='headimg/no-img.jpg', height_field=500, upload_to='headimg/', width_field=900),
        ),
    ]
