# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170425_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='暂无摘要', max_length=200),
        ),
    ]
