# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170424_2125'),
        ('blog', '0008_auto_20170425_2052'),
    ]

    operations = [
    ]
