# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyRecord',
        ),
    ]
