# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS', '0003_moneyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='关键词')),
                ('links', models.TextField(verbose_name='图片链接')),
            ],
        ),
        migrations.AlterField(
            model_name='moneyrecord',
            name='money_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='充值码'),
        ),
    ]
