# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS', '0004_auto_20170907_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名字')),
                ('cate', models.CharField(max_length=32, verbose_name='菜系')),
                ('detail_link', models.CharField(max_length=128, verbose_name='细节链接')),
                ('img_link', models.CharField(max_length=128, verbose_name='图片链接')),
            ],
            options={
                'verbose_name_plural': '美食',
            },
        ),
        migrations.AlterModelOptions(
            name='imageurl',
            options={'verbose_name_plural': '图片'},
        ),
    ]
