rules = {
    '指南': 'http://dwz.cn/ehcowechat',
    '爬虫': 'http://dwz.cn/ehcospider',
    '使用教程': '旧站点即将关闭了，新的请进Telegram群了解信息:\nhttps://t.me/Ehcobreakwa11',
    '客户端': 'http://mp.weixin.qq.com/s/iQDiW4PROIjQuxeOPy7K5g',
    '梯子': 'http://mp.weixin.qq.com/s/CtQwgcvztDTYstpMawLGow',
    '路由器': 'http://mp.weixin.qq.com/s/QiOlBCGZmNE7v0Z9Atc5Rg',
    '黑域': "链接:https://pan.baidu.com/s/1gfCEdnt 密码:v2ze",
    '妹纸图': '链接:https://pan.baidu.com/s/1qY2Rbq8 密码:rqv6',
    '妹子图': '链接:https://pan.baidu.com/s/1qY2Rbq8 密码:rqv6',
    '谜之屋': 'https://www.ehcozone.ml/ 请不要在微信直接打开',
    '网站': 'https://www.ehcozone.ml/ 请不要在微信直接打开',
    '群链接': 'https://t.me/Ehcobreakwa11',
    'telegram': 'https://t.me/Ehcobreakwa11',
}
